node:
  image:
    repository: 955967371588.dkr.ecr.us-east-1.amazonaws.com/devopsautomation
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  port: 5000
  replicaCount: 3
  type: ClusterIP

redis:
  image: public.ecr.aws/docker/library/redis:8.4-rc1-alpine
  port: 6379
  replicaCount: 1
  type: ClusterIP

nginx:
  image: public.ecr.aws/nginx/nginx:mainline
  port: 80
  servicePort: 80
  replicaCount: 1
  type: ClusterIP

  ingress:
    enabled: true
    className: "alb"
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    hosts:
      - host: dev.devops-s.live
        paths:
          - path: / 
            pathType: Prefix
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

