namespaceOverride: argocd
ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    lb.ingress.kubernetes.io/group.name: shared-alb
    external-dns.alpha.kubernetes.io/hostname: rollouts.sajil.click

  hosts:
    - host: rollouts.sajil.click
      paths:
        - path: / 
          pathType: Prefix
          backend:
            service:
              name: argo-rollouts-dashboard
              port:
                number: 3100