apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.node.port }}
    - name: metrics       # Prometheus metrics
      port: 5001
      targetPort: 5000
  type: ClusterIP
