apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 80
      name: metrics
      targetPort: {{ .Values.node.port }}
  type: ClusterIP
