apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-service-monitor
  labels:
    app.kubernetes.io/instance: prometheus-stack
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: node
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
