apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodeapp.fullname" . }}-nginx
  labels:
    {{- include "nodeapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.type }}
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nginx
