apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.node.name }}
  labels:
    app: node
spec:
  replicas: {{ .Values.node.replicaCount }}
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: {{ .Values.node.image}}
          ports:
            - containerPort: {{ .Values.node.port }}
          resources:
            {{- toYaml .Values.node.resources | nindent 12 }}
