apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "nodeapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.type }}
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: redis
