namespaceOverride: argocd

argocd:
  enabled: true
  namespace: argocd
  domainname: argocd.sajil.click
  ingress:
    enabled: true
    annotations:
      # Override specific annotations from default values.yaml
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:955967371588:certificate/58f46507-48af-4497-a836-43fb56b6b351
      external-dns.alpha.kubernetes.io/hostname: argocd.sajil.click
    hosts:
      - host: argocd.sajil.click
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-cd-argocd-server
                port:
                  number: 80

# Disable other components of the nodeapp chart if they are not needed in the argocd namespace
# This prevents deploying the nodeapp and nginx services/deployments into the argocd namespace.
node:
  replicaCount: 0
nginx:
  replicaCount: 0