name: Release Helm Chart

on:
  push:
    paths:
      - 'charts/**'   # run only when chart files change
    branches:
      - main          # or your default branch

permissions:
  contents: write     # required to push to gh-pages branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for index.yaml merge

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Package Helm chart
        run: |
          mkdir -p docs
          helm package charts/nginx-node-redis-helm-chart --destination docs

      - name: Update Helm repo index
        run: |
          helm repo index packaged --url https://sajil143pb.github.io/Helm/

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "chore: update helm chart package and index [skip ci]" || echo "No changes to commit"
          git push
